columnSuffix: null
handle: aboutText
instructions: null
name: 'About Text'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: dfd4603d-58c1-4595-b48a-f6d5e4412f40 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
