defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2f88f403-5336-4aef-906f-9c1a1c2b53aa # Project
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  eca632cd-4018-40c0-844b-908fceb8be43: # Audrey Stanton
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry.twig
    uriFormat: 'projects/{slug}'
type: channel
